apiVersion: v2
name: k3s-infrastructure
description: Core infrastructure components for K3s homelab cluster
type: application
version: 0.1.0
appVersion: "1.0"

maintainers:
  - name: homelab-admin
    email: admin@cluster.local

dependencies:
  - name: cert-manager
    version: "v1.15.0"
    repository: "https://charts.jetstack.io"
    condition: cert_manager.enabled
    
  - name: metallb
    version: "0.14.8"  
    repository: "https://metallb.github.io/metallb"
    condition: metallb.enabled
    
  - name: ingress-nginx
    version: "4.11.2"
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: ingress.enabled
    
  - name: argo-cd
    version: "7.4.1"
    repository: "https://argoproj.github.io/argo-helm"
    condition: argocd.enabled
    
  - name: kube-prometheus-stack
    version: "61.9.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: monitoring.enabled
    
  - name: longhorn
    version: "1.7.1" 
    repository: "https://charts.longhorn.io"
    condition: storage.longhorn.enabled
    
  - name: sealed-secrets
    version: "2.15.2"
    repository: "https://bitnami-labs.github.io/sealed-secrets"
    condition: sealed_secrets.enabled

keywords:
  - kubernetes
  - k3s
  - infrastructure
  - homelab
  - gitops

home: https://github.com/your-org/k3s-homelab-setup
sources:
  - https://github.com/your-org/k3s-homelab-setup

annotations:
  category: Infrastructure 