---
- name: Install Zsh
  apt:
    name: zsh
    state: present

- name: Install Oh My Zsh
  shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: /home/{{ ansible_user }}/.oh-my-zsh
  environment:
    ZSH: /home/{{ ansible_user }}/.oh-my-zsh
