---
# Web Browsers
- import_tasks: install_chrome.yaml
- import_tasks: install_firefox.yaml

# Communication Tools
- import_tasks: install_discord.yaml
- import_tasks: install_slack.yaml

# Media & Utilities
- import_tasks: install_vlc.yaml
- import_tasks: install_gimp.yaml 