---
- name: Ensure apt cache is up to date
  apt:
    update_cache: yes

- name: Install essential base packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - gh
    - vim
    - net-tools

- name: Install Helm
  shell: |
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm
