---
- name: Ensure apt cache is up to date
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install essential base packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - vim
      - net-tools
      - htop
      - gimp
      - curl
      - wget
