---
- name: Check if JetBrains Toolbox is installed
  command: ~/.local/bin/jetbrains-toolbox --version
  register: jetbrains_toolbox_installed
  failed_when: false
  changed_when: false
  ignore_errors: true

- name: Download JetBrains Toolbox
  get_url:
    url: https://data.services.jetbrains.com/products/download?code=TBA&platform=linux
    dest: /tmp/jetbrains-toolbox.tar.gz
  when: jetbrains_toolbox_installed.rc != 0

- name: Extract JetBrains Toolbox
  unarchive:
    src: /tmp/jetbrains-toolbox.tar.gz
    dest: /opt/
    remote_src: yes
  when: jetbrains_toolbox_installed.rc != 0

- name: Find extracted JetBrains Toolbox directories
  find:
    paths: /opt
    patterns: 'jetbrains-toolbox-*'
    file_type: directory
    recurse: no
  register: toolbox_dirs
  when: jetbrains_toolbox_installed.rc != 0

- name: Debug toolbox directories found
  debug:
    var: toolbox_dirs
  when: jetbrains_toolbox_installed.rc != 0

- name: Find the latest JetBrains Toolbox directory (by modification time)
  set_fact:
    toolbox_latest_dir: "{{ toolbox_dirs.files | sort(attribute='mtime') | last | default({}) }}"
  when: jetbrains_toolbox_installed.rc != 0 and toolbox_dirs.files | length > 0

- name: Debug selected toolbox directory
  debug:
    var: toolbox_latest_dir
  when: jetbrains_toolbox_installed.rc != 0

- name: Check if jetbrains-toolbox executable exists in the directory
  stat:
    path: "{{ toolbox_latest_dir.path }}/bin/jetbrains-toolbox"
  register: toolbox_executable
  when: jetbrains_toolbox_installed.rc != 0 and toolbox_latest_dir.path is defined

- name: Ensure .local/bin directory exists
  file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    mode: '0755'
  when: jetbrains_toolbox_installed.rc != 0

- name: Remove old symbolic link for JetBrains Toolbox if exists
  file:
    path: "{{ ansible_env.HOME }}/.local/bin/jetbrains-toolbox"
    state: absent
  when: jetbrains_toolbox_installed.rc != 0

- name: Create symbolic link for JetBrains Toolbox
  file:
    src: "{{ toolbox_latest_dir.path }}/bin/jetbrains-toolbox"
    dest: "{{ ansible_env.HOME }}/.local/bin/jetbrains-toolbox"
    state: link
  when: jetbrains_toolbox_installed.rc != 0 and toolbox_executable.stat.exists is defined and toolbox_executable.stat.exists

- name: Make JetBrains Toolbox executable
  file:
    path: "{{ toolbox_latest_dir.path }}/bin/jetbrains-toolbox"
    mode: '0755'
  when: jetbrains_toolbox_installed.rc != 0 and toolbox_executable.stat.exists is defined and toolbox_executable.stat.exists
