---
- name: Install essential packages for Go/GVM
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - bison
      - curl
      - git
      - build-essential
      - mercurial
      - binutils
      - gcc
      - make

- name: Check if GVM is already installed
  stat:
    path: "{{ ansible_env.HOME }}/.gvm/scripts/gvm"
  register: gvm_installed
  become: false

- name: Remove existing GVM installation if it exists in wrong location
  file:
    path: /root/.gvm
    state: absent
  when: ansible_user_id == 'root'

- name: Download GVM installer script
  get_url:
    url: https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer
    dest: "{{ ansible_env.HOME }}/gvm-installer"
    mode: '0755'
  become: false
  when: not gvm_installed.stat.exists

- name: Run GVM installer script
  shell: |
    bash {{ ansible_env.HOME }}/gvm-installer
  args:
    creates: "{{ ansible_env.HOME }}/.gvm"
  become: false
  when: not gvm_installed.stat.exists

- name: Remove GVM installer script
  file:
    path: "{{ ansible_env.HOME }}/gvm-installer"
    state: absent
  become: false
  when: not gvm_installed.stat.exists

- name: Ensure GVM is sourced in .zshrc
  blockinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK GVM"
    block: |
      [[ -s "{{ ansible_env.HOME }}/.gvm/scripts/gvm" ]] && source "{{ ansible_env.HOME }}/.gvm/scripts/gvm"
    create: yes
  become: false
  when: ansible_env.SHELL is defined and 'zsh' in ansible_env.SHELL

- name: Ensure GVM is sourced in .bashrc
  blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK GVM"
    block: |
      [[ -s "{{ ansible_env.HOME }}/.gvm/scripts/gvm" ]] && source "{{ ansible_env.HOME }}/.gvm/scripts/gvm"
    create: yes
  become: false
  when: ansible_env.SHELL is defined and 'bash' in ansible_env.SHELL

- name: Install latest stable Go version (binary)
  shell: |
    source {{ ansible_env.HOME }}/.gvm/scripts/gvm
    gvm install go1.23.4 -B
    gvm use go1.23.4 --default
  environment:
    HOME: "{{ ansible_env.HOME }}"
  args:
    executable: /bin/bash
  become: false

- name: Install useful Go tools
  shell: |
    source {{ ansible_env.HOME }}/.gvm/scripts/gvm
    gvm use go1.23.4
    go install golang.org/x/tools/...@latest
    go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    go install github.com/air-verse/air@latest
  environment:
    HOME: "{{ ansible_env.HOME }}"
  args:
    executable: /bin/bash
  become: false
  ignore_errors: yes

- name: Verify Go installation
  shell: |
    source {{ ansible_env.HOME }}/.gvm/scripts/gvm
    gvm use go1.23.4
    go version
  environment:
    HOME: "{{ ansible_env.HOME }}"
  args:
    executable: /bin/bash
  register: go_version
  changed_when: false
  become: false

- name: Display Go installation summary
  debug:
    msg: 
      - "Go version: {{ go_version.stdout }}"
      - "GVM installed at: {{ ansible_env.HOME }}/.gvm"
      - "Go tools installed: golang.org/x/tools, golangci-lint, air"
