---
- name: Create namespace for PostgreSQL
  command: kubectl create namespace postgres
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: Add Bitnami repository
  command: helm repo add bitnami https://charts.bitnami.com/bitnami

- name: Update Helm repositories
  command: helm repo update

- name: Install PostgreSQL with Helm
  shell: |
    helm install my-postgres bitnami/postgresql --namespace postgres
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
