---
- name: Check if Google Chrome is already installed
  command: google-chrome --version
  register: chrome_installed
  failed_when: false
  changed_when: false
  ignore_errors: true

- name: Install dependencies for Google Chrome
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - wget
      - gnupg
      - software-properties-common
  when: chrome_installed.rc != 0

- name: Download the Google Chrome .deb package
  get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/google-chrome-stable_current_amd64.deb
    mode: '0644'
  when: chrome_installed.rc != 0

- name: Install Google Chrome
  apt:
    deb: /tmp/google-chrome-stable_current_amd64.deb
    state: present
  when: chrome_installed.rc != 0

- name: Remove the Google Chrome .deb package
  file:
    path: /tmp/google-chrome-stable_current_amd64.deb
    state: absent
  when: chrome_installed.rc != 0

- name: Verify Google Chrome installation
  command: google-chrome --version
  register: chrome_version
  changed_when: false

- name: Display Chrome installation summary
  debug:
    msg: "Google Chrome version: {{ chrome_version.stdout }}"
