---
- name: Update package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Python 3 and essential packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - python3
      - python3-pip
      - python3-dev
      - python3-venv
      - python3-full
      - build-essential
      - python3-setuptools
      - python3-wheel

- name: Get user home directory
  shell: "echo $HOME"
  register: user_home
  become: false
  changed_when: false

- name: Check if python command exists
  command: which python
  register: python_exists
  failed_when: false
  changed_when: false

- name: Create symbolic link for python to python3 (if needed)
  file:
    src: /usr/bin/python3
    dest: /usr/bin/python
    state: link
    force: yes
  when: python_exists.rc != 0

- name: Ensure user's .local/bin directory exists
  file:
    path: "{{ user_home.stdout }}/.local/bin"
    state: directory
    mode: '0755'
  become: false

- name: Upgrade pip to latest version (user installation)
  pip:
    name: pip
    state: latest
    executable: pip3
    extra_args: --user
  become: false

- name: Install essential Python packages (user installation)
  pip:
    name: "{{ packages }}"
    executable: pip3
    extra_args: --user
    state: present
  vars:
    packages:
      - virtualenv
      - setuptools
      - wheel
      - requests
      - urllib3
  become: false

- name: Install data science packages (user installation)
  pip:
    name: "{{ packages }}"
    executable: pip3
    extra_args: --user
    state: present
  vars:
    packages:
      - numpy
      - pandas
      - matplotlib
      - scikit-learn
      - jupyter
      - notebook
      - ipython
  become: false
  register: data_science_install
  failed_when: false

- name: Ensure .local/bin is in PATH for zsh users
  blockinfile:
    path: "{{ user_home.stdout }}/.zshrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK PYTHON PATH"
    block: |
      # Add pip user bin to PATH
      export PATH="$HOME/.local/bin:$PATH"
    create: yes
  become: false
  when: ansible_env.SHELL is defined and 'zsh' in ansible_env.SHELL

- name: Ensure .local/bin is in PATH for bash users
  blockinfile:
    path: "{{ user_home.stdout }}/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK PYTHON PATH"
    block: |
      # Add pip user bin to PATH
      export PATH="$HOME/.local/bin:$PATH"
    create: yes
  become: false
  when: ansible_env.SHELL is defined and 'bash' in ansible_env.SHELL

- name: Verify Python installation
  command: python3 --version
  register: python_version
  changed_when: false

- name: Verify pip installation
  command: pip3 --version
  register: pip_version
  changed_when: false

- name: Display installation summary
  debug:
    msg:
      - "Python version: {{ python_version.stdout }}"
      - "Pip version: {{ pip_version.stdout }}"
      - "User packages installed to: {{ user_home.stdout }}/.local/"

- name: Display data science packages installation result
  debug:
    msg: "Data science packages installation: {{ 'successful' if not data_science_install.failed else 'failed - some packages may have dependency issues' }}"
