---
- name: Install dependencies for JetBrains Toolbox
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - wget
      - tar
      - fuse
      - libfuse2

- name: Get user home directory
  shell: "echo $HOME"
  register: user_home
  become: false
  changed_when: false

- name: Check if JetBrains Toolbox is already installed
  stat:
    path: /opt/jetbrains-toolbox
  register: toolbox_installed

- name: Create JetBrains Toolbox directory
  file:
    path: /opt/jetbrains-toolbox
    state: directory
    mode: '0755'
  when: not toolbox_installed.stat.exists

- name: Download JetBrains Toolbox
  get_url:
    url: https://download.jetbrains.com/toolbox/jetbrains-toolbox-2.6.3.43718.tar.gz
    dest: /tmp/jetbrains-toolbox.tar.gz
    mode: '0644'
  when: not toolbox_installed.stat.exists

- name: Extract JetBrains Toolbox
  unarchive:
    src: /tmp/jetbrains-toolbox.tar.gz
    dest: /opt/
    remote_src: yes
    creates: /opt/jetbrains-toolbox-2.6.3.43718
  when: not toolbox_installed.stat.exists

- name: Set permissions for JetBrains Toolbox executable
  file:
    path: /opt/jetbrains-toolbox-2.6.3.43718/bin/jetbrains-toolbox
    mode: '0755'
  when: not toolbox_installed.stat.exists

- name: Clean up downloaded archive
  file:
    path: /tmp/jetbrains-toolbox.tar.gz
    state: absent
  when: not toolbox_installed.stat.exists

- name: Check if JetBrains Toolbox executable exists
  stat:
    path: /opt/jetbrains-toolbox-2.6.3.43718/bin/jetbrains-toolbox
  register: toolbox_executable

- name: Ensure user's .local/bin directory exists
  file:
    path: "{{ user_home.stdout }}/.local/bin"
    state: directory
    mode: '0755'
  become: false

- name: Check if symlink already exists
  stat:
    path: "{{ user_home.stdout }}/.local/bin/jetbrains-toolbox"
  register: toolbox_symlink

- name: Create symlink to JetBrains Toolbox in user's local bin
  file:
    src: /opt/jetbrains-toolbox-2.6.3.43718/bin/jetbrains-toolbox
    dest: "{{ user_home.stdout }}/.local/bin/jetbrains-toolbox"
    state: link
    force: yes
  become: false
  when: toolbox_executable.stat.exists and not toolbox_symlink.stat.exists

- name: Verify JetBrains Toolbox installation
  command: "{{ user_home.stdout }}/.local/bin/jetbrains-toolbox --version"
  register: toolbox_version
  changed_when: false
  failed_when: false

- name: Display installation summary
  debug:
    msg:
      - "JetBrains Toolbox installed at: /opt/jetbrains-toolbox-2.6.3.43718/"
      - "Executable: /opt/jetbrains-toolbox-2.6.3.43718/bin/jetbrains-toolbox"
      - "Symlink created: {{ user_home.stdout }}/.local/bin/jetbrains-toolbox"
      - "Version check: {{ 'Success' if toolbox_version.rc == 0 else 'Failed - run toolbox manually first' }}"
      - "Launch with: jetbrains-toolbox"
