---
- name: Install Git
  apt:
    name:
      - git
      - gh
    state: present

- name: Configure git global user name
  git_config:
    name: user.name
    value: "Andres Orav"
    scope: global
  become: false

- name: Configure git global user email
  git_config:
    name: user.email
    value: "andres@orav.eu"
    scope: global
  become: false

- name: Configure git global editor
  git_config:
    name: core.editor
    value: "vim"
    scope: global
  become: false

- name: Configure git default branch name
  git_config:
    name: init.defaultBranch
    value: "main"
    scope: global
  become: false

- name: Configure git pull behavior
  git_config:
    name: pull.rebase
    value: "false"
    scope: global
  become: false

- name: Verify git configuration
  command: git config --global --list
  register: git_config_output
  changed_when: false
  become: false

- name: Display git configuration summary
  debug:
    msg:
      - "Git configuration completed for user: {{ ansible_user_id }}"
      - "User: Andres Orav <andres@orav.eu>"
      - "Editor: vim"
      - "Default branch: main"
