---
- name: Install dependencies for Cursor
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - wget
      - ca-certificates
      - gnupg
      - lsb-release
      - curl

- name: Get user home directory
  shell: "echo $HOME"
  register: user_home
  become: false
  changed_when: false

- name: Check if Cursor is already installed
  command: which cursor
  register: cursor_installed
  failed_when: false
  changed_when: false

- name: Create temporary directory for Cursor download
  tempfile:
    state: directory
    suffix: cursor
  register: cursor_temp_dir
  when: cursor_installed.rc != 0

- name: Get the actual Cursor download URL
  shell: |
    curl -s -I "https://www.cursor.com/api/download?platform=linux-x64&releaseTrack=stable" | grep -i location | cut -d' ' -f2 | tr -d '\r'
  register: cursor_download_url
  when: cursor_installed.rc != 0

- name: Download Cursor AppImage
  get_url:
    url: "{{ cursor_download_url.stdout | trim }}"
    dest: "{{ cursor_temp_dir.path }}/cursor.AppImage"
    mode: '0755'
    timeout: 300
    follow_redirects: all
    headers:
      User-Agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
  when: cursor_installed.rc != 0 and cursor_download_url.stdout | trim | length > 0

- name: Fallback - Download Cursor using curl if get_url fails
  shell: |
    curl -L -o "{{ cursor_temp_dir.path }}/cursor.AppImage" \
         -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36" \
         "https://www.cursor.com/api/download?platform=linux-x64&releaseTrack=stable"
    chmod +x "{{ cursor_temp_dir.path }}/cursor.AppImage"
  when: cursor_installed.rc != 0 and (cursor_download_url.stdout | trim | length == 0)

- name: Verify downloaded file is an AppImage
  shell: |
    file "{{ cursor_temp_dir.path }}/cursor.AppImage" | grep -i "executable"
  register: file_check
  failed_when: false
  when: cursor_installed.rc != 0

- name: Create Cursor installation directory
  file:
    path: /opt/cursor
    state: directory
    mode: '0755'
  when: cursor_installed.rc != 0

- name: Install Cursor AppImage
  copy:
    src: "{{ cursor_temp_dir.path }}/cursor.AppImage"
    dest: /opt/cursor/cursor.AppImage
    mode: '0755'
    remote_src: yes
  when: cursor_installed.rc != 0

- name: Create Cursor executable wrapper
  copy:
    dest: /usr/local/bin/cursor
    content: |
      #!/bin/bash
      exec /opt/cursor/cursor.AppImage "$@"
    mode: '0755'
  when: cursor_installed.rc != 0

- name: Clean up temporary directory
  file:
    path: "{{ cursor_temp_dir.path }}"
    state: absent
  when: cursor_installed.rc != 0 and cursor_temp_dir.path is defined

- name: Verify Cursor installation (with proper AppImage execution)
  shell: |
    if [ -x "/opt/cursor/cursor.AppImage" ]; then
      /opt/cursor/cursor.AppImage --version 2>/dev/null || echo "Cursor installed but version check failed"
    else
      echo "Cursor AppImage not found or not executable"
      exit 1
    fi
  register: cursor_version_check
  changed_when: false
  failed_when: false

- name: Create Cursor desktop entry
  copy:
    dest: /usr/share/applications/cursor.desktop
    content: |
      [Desktop Entry]
      Name=Cursor
      Comment=The AI-first code editor
      GenericName=Text Editor
      Exec=cursor %F
      Icon=cursor
      Type=Application
      StartupNotify=true
      StartupWMClass=Cursor
      Categories=TextEditor;Development;IDE;
      MimeType=text/plain;inode/directory;
      Actions=new-empty-window;
      Keywords=cursor;editor;ide;development;ai;

      [Desktop Action new-empty-window]
      Name=New Empty Window
      Exec=cursor --new-window %F
      Icon=cursor
    mode: '0644'
  when: cursor_installed.rc != 0

- name: Add Cursor to user's local bin (symlink)
  file:
    src: /usr/local/bin/cursor
    dest: "{{ user_home.stdout }}/.local/bin/cursor"
    state: link
    force: yes
  become: false
  when: cursor_installed.rc != 0

- name: Display Cursor installation summary
  debug:
    msg:
      - "Cursor installation completed"
      - "Status: {{ cursor_version_check.stdout if cursor_version_check.stdout is defined else 'Installation attempted' }}"
      - "Executable: /usr/local/bin/cursor"
      - "AppImage: /opt/cursor/cursor.AppImage"
      - "Desktop entry: /usr/share/applications/cursor.desktop"
      - "User symlink: {{ user_home.stdout }}/.local/bin/cursor"
      - "You can launch Cursor from applications menu or run 'cursor' in terminal" 