---
- name: Get user home directory
  shell: "echo $HOME"
  register: user_home
  become: false
  changed_when: false

- name: Check if NVM is already installed
  stat:
    path: "{{ user_home.stdout }}/.nvm/nvm.sh"
  register: nvm_installed
  become: false

- name: Install dependencies for NVM
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - curl
      - build-essential
      - libssl-dev

- name: Download and install NVM
  shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
  args:
    creates: "{{ user_home.stdout }}/.nvm"
  become: false
  when: not nvm_installed.stat.exists

- name: Add NVM to .zshrc
  blockinfile:
    path: "{{ user_home.stdout }}/.zshrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK NVM"
    block: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
    create: yes
  become: false
  when: ansible_env.SHELL is defined and 'zsh' in ansible_env.SHELL

- name: Add NVM to .bashrc
  blockinfile:
    path: "{{ user_home.stdout }}/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK NVM"
    block: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
    create: yes
  become: false
  when: ansible_env.SHELL is defined and 'bash' in ansible_env.SHELL

- name: Install latest LTS Node.js
  shell: |
    export NVM_DIR="{{ user_home.stdout }}/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    nvm install --lts
    nvm use --lts
    nvm alias default "lts/*"
  environment:
    HOME: "{{ user_home.stdout }}"
  args:
    executable: /bin/bash
  become: false

- name: Install useful global npm packages
  shell: |
    export NVM_DIR="{{ user_home.stdout }}/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    nvm use --lts
    npm install -g yarn pnpm typescript ts-node nodemon eslint prettier
  environment:
    HOME: "{{ user_home.stdout }}"
  args:
    executable: /bin/bash
  become: false
  ignore_errors: yes

- name: Verify Node.js installation
  shell: |
    export NVM_DIR="{{ user_home.stdout }}/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    nvm use --lts
    node --version && npm --version
  environment:
    HOME: "{{ user_home.stdout }}"
  args:
    executable: /bin/bash
  register: node_version
  changed_when: false
  become: false

- name: Verify global packages installation
  shell: |
    export NVM_DIR="{{ user_home.stdout }}/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    nvm use --lts
    npm list -g --depth=0
  environment:
    HOME: "{{ user_home.stdout }}"
  args:
    executable: /bin/bash
  register: npm_globals
  changed_when: false
  become: false
  ignore_errors: yes

- name: Display Node.js installation summary
  debug:
    msg: 
      - "Node.js and npm versions: {{ node_version.stdout }}"
      - "NVM installed at: {{ user_home.stdout }}/.nvm"
      - "Global packages: yarn, pnpm, typescript, ts-node, nodemon, eslint, prettier"
