---
- name: Create namespace for Kafka
  shell: kubectl create namespace kafka || kubectl get namespace kafka
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  changed_when: false

- name: Add Bitnami repository
  command: helm repo add bitnami https://charts.bitnami.com/bitnami
  failed_when: false
  changed_when: false

- name: Update Helm repositories
  command: helm repo update

- name: Deploy Kafka
  shell: |
    helm install my-kafka bitnami/kafka --namespace kafka
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: Wait for Kafka pods to be ready
  shell: |
    kubectl wait --namespace kafka --for=condition=ready pod -l app.kubernetes.io/name=kafka --timeout=300s
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
