---
- name: Create namespace
  command: kubectl create namespace kafka

- name: Add Bitnami repository
  command: helm repo add bitnami https://charts.bitnami.com/bitnami

- name: Update Helm repositories
  command: helm repo update

- name: Deploy Kafka
  shell: |
      helm install my-kafka bitnami/kafka --namespace kafka
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: Wait for Kafka pods to be ready
  shell: |
    kubectl wait --namespace kafka --for=condition=ready pod -l app.kubernetes.io/name=kafka --timeout=300s
