# Development Environment Configuration - Localhost Only Setup
---
global:
  environment: dev
  domain: "dev.localhost"
  cluster_name: "k3s-dev-local"

# ArgoCD Configuration - Minimal for dev
argocd:
  enabled: false  # Disabled for localhost dev - use production cluster for GitOps testing
  domain: "argocd.dev.localhost"
  admin_password: "dev123!"
  cert_issuer: "selfsigned"  # Use self-signed for dev
  oidc_enabled: false
  resources:
    server:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    controller:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

# cert-manager Configuration - Self-signed for dev
cert_manager:
  enabled: true
  cert_issuer: "selfsigned"  # No external dependencies
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 50m
      memory: 64Mi
  create_wildcard_cert: false

# MetalLB Configuration - Disabled for localhost
metallb:
  enabled: false  # Use NodePort services for localhost dev
  ip_pool:
    addresses: []
  resources:
    controller:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi

# Monitoring Configuration - Minimal stack
monitoring:
  enabled: true
  prometheus:
    retention: "3d"  # Short retention for dev
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi
  grafana:
    enabled: true
    admin_password: "dev123"
    service_type: "NodePort"  # Easy localhost access

# Ingress Configuration - Minimal or disabled
ingress:
  enabled: false  # Use NodePort/port-forward for localhost
  class: "nginx"
  tls_enabled: false

# Storage Configuration - Local only
storage:
  longhorn:
    enabled: false  # Use local storage in dev
  backup:
    enabled: false

# Security Configuration - Relaxed for dev
security:
  networkpolicies: false  # Disabled for dev flexibility
  podsecuritypolicies: false

# Sealed Secrets Configuration - Simplified
sealed_secrets:
  enabled: false  # Use regular secrets for dev simplicity
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
  log_level: "debug"

# External DNS - Disabled for localhost
external_dns:
  enabled: false

# Development-specific settings
dev_settings:
  # Enable development tools
  kubectl_proxy: true
  debug_logging: true

  # Resource limits are relaxed
  resource_quotas_enabled: false

  # Fast feedback loop settings
  reconciliation_interval: "30s"

  # Development convenience features
  auto_restart_on_config_change: true
