---
- name: Ensure apt cache is up to date
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install media packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - gimp
      - vlc
