apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: postgres-server
data:
  main-config: |
    # PostgreSQL configuration content here
    # Example configuration
    shared_buffers = 128MB
    max_connections = 100
