apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argocd
  labels:
    app.kubernetes.io/name: applications
    app.kubernetes.io/part-of: gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/your-org/k3s-homelab-setup
      revision: HEAD
      directories:
      - path: gitops/applications/*
      template:
        metadata:
          labels:
            app.kubernetes.io/managed-by: argocd-applicationset
        spec:
          source:
            repoURL: https://github.com/your-org/k3s-homelab-setup
            targetRevision: HEAD
          project: default
          destination:
            server: https://kubernetes.default.svc
  - list:
      elements:
      - environment: dev
        cluster: k3s-dev
        url: https://kubernetes.default.svc
        namespace_suffix: "-dev"
        values_file: environments/dev/values.yaml
        auto_sync: true
      - environment: staging
        cluster: k3s-staging
        url: https://k3s-staging.cluster.local  
        namespace_suffix: "-staging"
        values_file: environments/staging/values.yaml
        auto_sync: true
      - environment: production
        cluster: k3s-production
        url: https://k3s-production.cluster.local
        namespace_suffix: ""
        values_file: environments/production/values.yaml
        auto_sync: false  # Manual sync for production
        
  template:
    metadata:
      name: '{{path.basename}}-{{environment}}'
      labels:
        environment: '{{environment}}'
        cluster: '{{cluster}}'
        component: application
        application: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/your-org/k3s-homelab-setup
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles:
          - '../{{values_file}}'
          parameters:
          - name: global.environment
            value: '{{environment}}'
          - name: global.cluster  
            value: '{{cluster}}'
          - name: global.namespace_suffix
            value: '{{namespace_suffix}}'
      destination:
        server: '{{url}}'
        namespace: '{{path.basename}}{{namespace_suffix}}'
      syncPolicy:
        automated:
          prune: '{{auto_sync}}'
          selfHeal: '{{auto_sync}}'
          allowEmpty: false
        syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      revisionHistoryLimit: 5 