---
# Example Sealed Secret for Development Environment
# This demonstrates how secrets are stored in the GitOps repository
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: example-app-secrets
  namespace: default
  labels:
    app: example-app
    environment: dev
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "false"
    sealedsecrets.bitnami.com/namespace-wide: "false"
spec:
  encryptedData:
    # NOTE: These are example encrypted values - replace with actual sealed values
    # Created using: echo -n 'dev-password123' | kubeseal --raw --from-file=/dev/stdin --name=example-app-secrets --namespace=default
    database-password: "AQAAABBCCDDEEFFGGHHIIJJKKLLMMNNOOPPQQRRSSTTUUVVWWXXYYZZaaaa..."
    database-username: "AQAAAAbbccddEEFFGGHHIIJJKKLLMMNNOOPPQQRRSSTTUUVVWWXXYYZZbbbb..."
    api-key: "AQAAAAccddEEFFGGHHIIJJKKLLMMNNOOPPQQRRSSTTUUVVWWXXYYZZcccc..."
    redis-password: "AQAAAAddEEFFGGHHIIJJKKLLMMNNOOPPQQRRSSTTUUVVWWXXYYZZdddd..."
  template:
    metadata:
      name: example-app-secrets
      namespace: default
      labels:
        app: example-app
        environment: dev
    type: Opaque
---
# The above SealedSecret will create a regular Secret like this:
# apiVersion: v1
# kind: Secret
# metadata:
#   name: example-app-secrets
#   namespace: default
#   labels:
#     app: example-app
#     environment: dev
# type: Opaque
# data:
#   database-password: ZGV2LXBhc3N3b3JkMTIz  # dev-password123 (base64)
#   database-username: ZGV2dXNlcg==           # devuser (base64)
#   api-key: ZGV2LWFwaS1rZXktMTIz             # dev-api-key-123 (base64)
#   redis-password: cmVkaXMtZGV2LXBhc3M=      # redis-dev-pass (base64) 